<%@ page pageEncoding="UTF-8" %>
      <!-- The Scripts -->
      <script src="js/jquery.min.js"></script>
      <script src="js/jquery-migrate-1.2.1.min.js"></script>
      <script src="js/jquery-ui.js"></script>
      <script src="js/bootstrap.js"></script>
      <script src="js/jquery.parallax.js"></script>
      <script src="js/jquery.wait.js"></script>
      <script src="js/modernizr-2.6.2.min.js"></script>
      <script src="js/modernizr.custom.js"></script>
      <script src="js/revolution-slider/js/jquery.themepunch.tools.min.js"></script>
      <script src="js/revolution-slider/js/jquery.themepunch.revolution.min.js"></script>
      <script src="js/jquery.nivo.slider.pack.js"></script>
      <script src="js/jquery.prettyPhoto.js"></script>
      <script src="js/superfish.js"></script>
      <script src="js/tweetMachine.js"></script>
      <script src="js/tytabs.js"></script>
      <script src="js/jquery.gmap.min.js"></script>
      <script src="js/circularnav.js"></script>
      <script src="js/jquery.sticky.js"></script>
      <script src="js/jflickrfeed.js"></script>
      <script src="js/imagesloaded.pkgd.min.js"></script>
      <script src="js/waypoints.min.js"></script>
      <!-- <script src="http://maps.google.com/maps/api/js?sensor=false"></script> -->
      <script src="js/jquery.gmap.min.js"></script>
      <script src="js/custom.js"></script>
    <script src="app.js" ></script>
