name: Check Pull Request with Maven

on:
  pull_request:
    branches: [ c8-demo-setup ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Package with Maven
        run: mvn clean package
      - name: Build docker image
        run: docker build .
        env:
          DOCKER_BUILDKIT: 1